branches:
  only:
    - master

language: python

python:
  - 2.7

sudo: false

env:
  global:
    - APPENGINE_SDK_VERSION=1.9.24
  matrix:
    - DJANGO_VERSION=1.4
    - DJANGO_VERSION=1.5
    - DJANGO_VERSION=1.6

install:
  - pip install git+http://github.com/django-nonrel/django@nonrel-$DJANGO_VERSION\#egg=django --target=$PWD
  - pip install git+http://github.com/django-nonrel/djangotoolbox@master\#egg=djangotoolbox --target=$PWD
  - pip install git+http://github.com/django-nonrel/django-dbindexer@master\#egg=django-dbindexer --target=$PWD
  - pip install git+https://github.com/adieu/django-autoload\#egg=django-autoload --target=$PWD
  - pip install Pillow
  - pip install GoogleAppEngineCloudStorageClient

before_script:
  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_$APPENGINE_SDK_VERSION.zip -nv
  - unzip -q google_appengine_$APPENGINE_SDK_VERSION.zip
  - PYTHONPATH=. python django/bin/django-admin.py startproject --name=app.yaml --template=djangoappengine/conf/project_template appenginetest .

script: ./manage.py test djangoappengine djangotoolbox dbindexer
