# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snakr', '0002_citylog_countrylog_eventlog_hostlog_iplog_longurls_shorturls_useragentlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlog',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='citylog',
            name='is_blacklisted',
            field=models.CharField(default=b'N', max_length=1, verbose_name=b'If Y, 403 any request received containing this value.'),
        ),
        migrations.AddField(
            model_name='countrylog',
            name='is_blacklisted',
            field=models.CharField(default=b'N', max_length=1, verbose_name=b'If Y, 403 any request received containing this value.'),
        ),
        migrations.AddField(
            model_name='hostlog',
            name='is_blacklisted',
            field=models.CharField(default=b'N', max_length=1, verbose_name=b'If Y, 403 any request received containing this value.'),
        ),
        migrations.AddField(
            model_name='iplog',
            name='is_blacklisted',
            field=models.CharField(default=b'N', max_length=1, verbose_name=b'If Y, 403 any request received containing this value.'),
        ),
        migrations.AddField(
            model_name='useragentlog',
            name='is_blacklisted',
            field=models.CharField(default=b'N', max_length=1, verbose_name=b'If Y, 403 any request received containing this value.'),
        ),
    ]
