# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snakr', '0003_auto_20160314_2359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citylog',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='countrylog',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='hostlog',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='iplog',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='useragentlog',
            options={'managed': False},
        ),
    ]
