# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snakr', '0005_auto_20160315_0003'),
    ]

    operations = [
    ]
